# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Season of Code
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website of b-brankovics. I am a bioinformatician and a hobby developer.
  This website is a collection of projects and my blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://b-brankovics.github.io" # the base hostname & protocol for your site
twitter_username: BBrankovics
github_username:  b-brankovics

# Build settings
markdown: kramdown
